### ISSUE TITLE
Choose Monitor for notifications

### ISSUE THREAD

**Issue by Jamie-505** [phuhl/linux_notification_center#1]
Feature Request:
Add an option to choose a monitor to display the notifications and the center ( like dunst does)
An follow option would also be nice (show notifications on focused screen)

**Comment by phuhl** [comment]
Hey @Jamie-505, I pushed half a fix for this to [feature_monitorsupport](https://github.com/phuhl/linux_notification_center/tree/feature_monitorsupport). It adds support for selecting which monitor to show on, not for following, yet.

As I do not have access to a multi monitor setup right now, I'd be thrilled to get some feedback on it working or not.

**Comment by phuhl** [comment]
So, if anybody has the multi-monitor setup, feel free to test this branch so I can merge it, otherwise it will take some more time until I can do it.

**Comment by Jamie-505** [comment]
I finally had time to test this. Seems like it works. I can send the center and the notis to the screen of my liking. Not sure if there's also an option to show them on all screens simultaneously (therefore I haven't tested this scenario).

**Comment by paperbenni** [comment]
I have a multi monitor setup and would like to request another feature. As of now, you can configure which monitor the sidebar shows on, but you're going to be stuck with it. It would be really helpful if there was an option that made it appear on the monitor the mouse cursor/window focus is currently on. (like dunst already has)

**Comment by phuhl** [comment]
Funny enough the current feature doesn't even work on my system. I currently don't have the time to work on this, but maybe I will build it in the future. Thnaks for the feedback though.

**Comment by phuhl** [comment]
A recent commit added the feature requested by @paperbenni :) Is not in the AUR yet, but will be at some point soon. Should you test it, feel free to give me feedback if everything works ok.
