### ISSUE TITLE
Text too long for row?

### ISSUE THREAD

**Issue by Xananax** [phuhl/linux_notification_center#10]
It seems that this is what this message is saying (my german is rusty)

![image](https://user-images.githubusercontent.com/836082/57998368-dd409580-7ad9-11e9-86d5-d3397cb82be8.png)

It seems to be happening when an image should be included, but I am not sure

**Comment by phuhl** [comment]
Thank you for reporting, I fixed it. This is a duplicate of #19, an update will follow shortly
