### ISSUE TITLE
Clear All button not showing up after some time

### ISSUE THREAD

**Issue by Alumniminium** [phuhl/linux_notification_center#103]
![screenshot](https://cdn.her.st/images/1604392287.webp)

sometimes, after I've got a number of notifications so I can scroll, the Clear button or w/e it's called doesn't show up anymore.

I'm on an up-to-date arch install and I use bspwm

**Comment by phuhl** [comment]
Thanks for reporting.

My guess is, that in that case there is a too wide notification, extending the notification center too far to the right. The  button is right aligned and will be outside of your view.

I guess, that the notifications don't have a close button anymore, either. Is that the case?

**Comment by Alumniminium** [comment]
> I guess, that the notifications don't have a close button anymore, either. Is that the case?

Yeah, that's the case too, seems to be offscreen as you said.
