### ISSUE TITLE
Rounded corners on the notification center?

### ISSUE THREAD

**Issue by vpcano** [phuhl/linux_notification_center#105]
Hi. Is there any way to achieve rounded corners on the notification center? I tried adding `border-radius` property to `.deadd-noti-center` class at `gtk.css` but nothing happened.

**Comment by phuhl** [comment]
Hey there, deadd does not support rounded corners, currently. You can get them, though, if you use [Picom with rounded corners](https://aur.archlinux.org/packages/picom-rounded-corners/). Picom is a compositor, that was forked from compton. Let me know, what you think

**Comment by Barbarossa93** [comment]
@phuhl Is that just for the actual notifications and the edges of the notification center? I'd like to be able to round the buttons in the notification center as well as images in notifications

**Comment by phuhl** [comment]
Thats just the notification box and the notification center.

You can achieve rounded corners for buttons, etc. by editing https://github.com/phuhl/linux_notification_center/blob/master/style.css and recompiling. I don't think, there is an easier way, currently.

If you feel adventurous, feel free, to create a PR that introduces config-options for this ;)

**Comment by phuhl** [comment]
I'll close this as the new CSS styling feature allows to add border-radius to any element one desires. For more information, see https://github.com/phuhl/linux_notification_center#css-styling
