### ISSUE TITLE
More comments in the default deadd.conf

### ISSUE THREAD

**Issue by nelimee** [phuhl/linux_notification_center#11]
I am currently trying to configure deadd to match with the style of my system and I found myself struggling with the default configuration file and customization. Some of the problems I found:

1. Several option names are hard to understand. I had to test by changing only some values and restarting each time the X server with the deadd-notification-center daemon to understand the meaning of some options.
2. Some options names are duplicated in different sections. For example `buttonColor` is in the sections `[colors]` **and** `buttons`, with a different behaviour.
3. The default option for `buttonBackground` in the section `[colors]` is `transparent`. But are there any alternatives? If yes, how can I learn about them?

A first solution would be to add comments to explain each section/option in details. 
I think changing the names of some options might be beneficial, but not as much as adding proper comments above each option.

I will probably send a pull request in the following days with some of the comments I wished to have a few days ago. I couldn't find the meaning/default values for some options though, for example the `buttonBackground` possible values.

PS: Thanks for the nice and configurable tool! Nice job :)

**Comment by nelimee** [comment]
Here is the [commented version](https://gist.github.com/nelimee/72ea7344c3d7e821bb569ae66ab78b61).

Each line beginning with "# NOTE:" is either a question or a suggestion. You are free to do whatever you want with it.

**Comment by phuhl** [comment]
Hey @nelimee, thanks for the commented version. I am currently stuck with a lot of work on my masters thesis, but when I have a little spare time, I will read your version and put it in this repo. Thanks for the nice feedback :)

**Comment by phuhl** [comment]
Hey @nelimee, I found time to take your notes and complete them. You will see them in the README as soon as I push the changes. I am not sure, how I feel about renaming config-options. You are right, that some are awfully named, but by now, I probably brake someones setup when I change the names. As I hate that kind of instability myself, for now, better comments have to do the trick, I am afraid. Anyways, good work on these comments, thanks for the contribution!

**Comment by phuhl** [comment]
If some options are still unclear, feel free to open a new issue and ask about them ;)
