### ISSUE TITLE
Display notification in center only without pop-up

### ISSUE THREAD

**Issue by weilbith** [phuhl/linux_notification_center#111]
Hey,
thank you for this pretty damn cool project!
I was wonderin if it is somehow possible to add a hint to a notification so that it directly lands in the notification center and no pop-up gets shown.
Thanks for your help!d

**Comment by phuhl** [comment]
Hey, thanks for the feedback.

It does'nt appear that https://developer.gnome.org/notification-spec/#hints has a hint defined for that usecase. It currently is not implemented, either. 

Currently, a **very** hackish way could be

```sh
# pause popup notifications
notify-send.py a --hint boolean:deadd-notification-center:true \
                 string:type:pausePopups

## send notification here

# unpause popup notifications
notify-send.py a --hint boolean:deadd-notification-center:true \
                 string:type:unpausePopups
```

In the future we could introduce a dedicated hint for this

**Comment by phuhl** [comment]
You could also use a very short expiration time for the notification (not 0 or -1 as they have special meanings). Also, not a great solution...

**Comment by weilbith** [comment]
> In the future we could introduce a dedicated hint for this

That would be pretty neat! Is it complicated to add?

> not 0 or -1 as they have special meanings

Which special meanings? Would be actually cool if it was possible to just set it to such value and don't add a new exotic hint. :thinking: 

---

I must admit that I have more ulterior motives: would it be a possible feature to have notifications that are sticky in the center? At the bottom eventually?
I'm eventually having thoughts that go against your design approach. But I like the notification and applet center of OS X. I kinda dislike to have such information like next calendar meeting or current music track in the status line. But having plain notifications that always pop-up and disappear are also not a nice solution. Taking the music as an example, I think it is more like you actively want to know the current track at a specific point in time rather then you want to get notified all the time with shortly shown messages. But the event based approach (as notifications work...) and your great design are appealing to kind of pushing updates as notifications that always replace the last notification of the same tool (like music or calendar). But even they would not pop-up and only show up in the notification center, they would still get pushed down by other notifications, are always displayed at a different location or just disappear at the bottom of the screen. Therefore I'm asking about the stickyness.

Sorry to annoy with such thoughts. I'm hesitantly searching for alternatives, but I simply can't find anything promising.

**Comment by phuhl** [comment]
> That would be pretty neat! Is it complicated to add?

Technically speaking, no. But i am a little tight on time currently. You can always create a PR of course :)

I like the stickyness, but that should be a new issue...

**Comment by weilbith** [comment]
Cool. Thanks for the feedback. :upside_down_face: 
I have absolutely no clue about Haskell and I'm also limited on time atm. So I'm just subscribing to the issues. :upside_down_face:
