### ISSUE TITLE
[BUG] runCommand from System.Process leaves zombie child process.

### ISSUE THREAD

**Issue by ahmubashshir** [phuhl/linux_notification_center#126]
`runCommand` holds the child in process table without reaping it. The notification center should handle `SIGCLD` properly and reap the dead child process.

![image](https://user-images.githubusercontent.com/24864366/103737982-73ae2b80-501d-11eb-88b2-a19dc1929683.png)
![image](https://user-images.githubusercontent.com/24864366/103738248-dbfd0d00-501d-11eb-9fa6-2d7140abf129.png)

**Comment by phuhl** [comment]
This might be an upstream issue. Only thing we can do here is open an issue upstream or/and replace runCommand with something, I guess
