### ISSUE TITLE
dead.css not working and using the reloadStyle causes deadd-notification-center to crash

### ISSUE THREAD

**Issue by deadbody13** [phuhl/linux_notification_center#129]
The two config files as I have them are ~/.config/deadd/deadd.conf and ~/.config/deadd/deadd.css. The deadd.conf is loading just fine but the deadd.css isn't loading anything at all and using the `notify-send.py a --hint boolean:deadd-notification-center:true type:reloadStyle` will cause it to crash. Though I'm using the deadd.css from the README, I have tried using things like basic color and outline attributes, nothing would show up on the DNC.

Running `deadd-notification-center` from terminal and then running the reload script results in the following message:

`deadd-notification-center: src/NotificationCenter.hs:(247,16)-(263,65): Non-exhaustive patterns in case`

I first installed the DNC with `yay` and after the issues showed up I tried installing `notify-send.py` from source, thinking that might help, it didn't change anything. I swept through the README and installed anything mentioned as a dependency, and tried using `makepkg` on the binary instead of installing it through `yay`.

OS: Arch Linux (5.10.6-arch1-1)
DE: i3-gaps
[~/.config/deadd/deadd.conf](https://gitlab.com/Deadbody13/configfiles/-/blob/master/deadd/deadd.conf) 
[~/.config/deadd/deadd.css](https://gitlab.com/Deadbody13/configfiles/-/blob/master/deadd/deadd.css) 

### === Solution Found ===
_or at least something to make my problem go away_
I went back and ran `yay -S deadd-notification-center-git` in place of `yay -S deadd-notification-center-bin` and now everything is working, the reload script included.

**Comment by MyriaCore** [comment]
Ohhh yeah the bin is outdated, the newer features would be in the git repository.
