### ISSUE TITLE
Installer does not create deadd.css

### ISSUE THREAD

**Issue by phuhl** [phuhl/linux_notification_center#132]
As noted here: https://github.com/phuhl/linux_notification_center/issues/127

For @MyriaCore no dead.css was created upon installation, but should have been

**Comment by mikenrafter** [comment]
At least on the nix side of things, the `.conf` file is missing too.

**Comment by phuhl** [comment]
deadd.css issue is resolved. Reg. nix: Package is provided by a third party, you'd have to ping them to update their package.
