### ISSUE TITLE
Make the README.org mobile responsive

### ISSUE THREAD

**Issue by bnainar** [phuhl/linux_notification_center#152]
It's very difficult to view the README on mobile device. Please use standard markdown

**Comment by phuhl** [comment]
Are you referring to the "news" section or the rest, too?

**Comment by bnainar** [comment]
@phuhl, ofcourse yes. I tried to contribute, but it seems it's not markdown

**Comment by phuhl** [comment]
Indeed, it's not markdown but org-mode, a different markup language. The news-section itself is just a bit of fun with ASCII art I made to celebrate some changes and the contributions of the last year. All the important information (below the news section) should be accessible on a mobile device.

I don't want to remove the news section. Maybe a notice above it could help, to inform mobile readers, that accessible content is available further down.

**Comment by phuhl** [comment]
Moved the news section to the new discussions-section
