### ISSUE TITLE
No way to escape markup

### ISSUE THREAD

**Issue by The-Compiler** [phuhl/linux_notification_center#159]
When the `markup` capability is advertised, applications escape `<`, `>` and `&` in the data they send - see the [notification spec](https://specifications.freedesktop.org/notification-spec/latest/ar01s04.html) and [Ubuntu guidelines](https://wiki.ubuntu.com/NotificationDevelopmentGuidelines#If_a_notification_uses_a_.2BIBw.3C.2BIB0_or_.2BIBw.26.2BIB0_character.2C_and_it_has_missing_or_wrong_text) for details.

However, with linux_notification_center (the 1.7.2 release binary with default config), doing:

`notify-send foo '&lt;&lt foo &gt; &gt;'`

leads to that text being displayed literally, while:

`notify-send foo '<< foo >>'`

doesn't display the body at all.

**Comment by phuhl** [comment]
Just checked, seems to be fixed
