### ISSUE TITLE
No XDG_CONFIG_HOME support

### ISSUE THREAD

**Issue by GaugeK** [phuhl/linux_notification_center#16]
Currently this hard-codes ~/.config, which is a pain for people who use an abnormal home layout.

A variables exists that is used to change this ($XDG_CONFIG_HOME), but it isn't set by default on most distros, so you'd need to check if it exists and use it accordingly. (In sh this can be done by using `${XDG_CONFIG_HOME:-~/.config}`, but I'm not sure how to do it in haskell.)

**Comment by phuhl** [comment]
Thanks for reporting, will be fixed in the next update :)
