### ISSUE TITLE
Declare spec 1.2 support?

### ISSUE THREAD

**Issue by The-Compiler** [phuhl/linux_notification_center#160]
linux_notification_center (the 1.7.2 release binary) seems to advertise support for the 1.0 spec only:

```
$ dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation method return time=1616873197.040897 sender=:1.60612 -> destination=:1.60632 serial=46 reply_serial=2
   string "haskell-notification-daemon"
   string "abc"
   string "0.0.1"
   string "1.0"
```

The main difference between the spec versions (as far as I know) is the [name of the image data hint](https://specifications.freedesktop.org/notification-spec/latest/ar01s08.html). From what I can gather, haskell-notification-daemon seems to (fully?) implement the 1.2 spec, not only 1.0.

**Comment by phuhl** [comment]
Thanks, fixed
