### ISSUE TITLE
Customize L-N-C

### ISSUE THREAD

**Issue by P4NAD3ROXIS** [phuhl/linux_notification_center#164]
How can I resize the notification-center.

**Comment by phuhl** [comment]
Can you explain, what exactly you want to do?

**Comment by P4NAD3ROXIS** [comment]
I want to resize and change the background color

**Comment by ahmubashshir** [comment]
use deadd.conf and deadd.css

**Comment by mikenrafter** [comment]
Hate to be rude here, but RTFM.  
It's on the github page, if you're wondering. It's quite informative!

More specifically, search for `/^width\s*=\s*/g` in your `.conf` file.
