### ISSUE TITLE
Not in scope: HarfBuzz.Callbacks.C_FontGetGlyphExtentsFuncT

### ISSUE THREAD

**Issue by igorepst** [phuhl/linux_notification_center#165]
Hi, I have an issue when compiling the git version from AUR package on ArchLinux:

    gi-harfbuzz              > /tmp/stack-f1db3c4da7f82da0/gi-harfbuzz-0.0.3/GI/HarfBuzz/Functions.hs:22105:12: error:
    gi-harfbuzz              >     Not in scope:
    gi-harfbuzz              >       type constructor or class ‘HarfBuzz.Callbacks.C_FontGetGlyphExtentsFuncT’
    gi-harfbuzz              >     Perhaps you meant one of these:
    gi-harfbuzz              >       ‘HarfBuzz.Callbacks.C_FontGetGlyphAdvanceFuncT’ (imported from GI.HarfBuzz.Callbacks),
    gi-harfbuzz              >       ‘HarfBuzz.Callbacks.C_FontGetGlyphAdvancesFuncT’ (imported from GI.HarfBuzz.Callbacks),
    gi-harfbuzz              >       ‘HarfBuzz.Callbacks.C_FontGetGlyphNameFuncT’ (imported from GI.HarfBuzz.Callbacks)
    gi-harfbuzz              >     Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_FontGetGlyphExtentsFuncT’.
    gi-harfbuzz              >       |   
    gi-harfbuzz              > 22105 |     FunPtr HarfBuzz.Callbacks.C_FontGetGlyphExtentsFuncT -> -- func : TInterface (Name {namespace = "HarfBuzz", name = "font_get_glyph_extents_func_t"})

How it can be resolved? Thank you

**Comment by mbrea-c** [comment]
Same problem here, compiling from latest commit. Did you find a solution?

**Comment by igorepst** [comment]
Nope, I just used the precompiled executable from yhe '.out' folder of the source tree.
@phuhl Can you help, please?

**Comment by mbrea-c** [comment]
Alright, so I managed to fix it by updating ```gi-harfbuzz``` to the latest version in ```stack.yaml```, and resolving conflicts by updating other dependencies as well. The resulting ```extra-deps``` section of stack.yaml ends up looking something like this:
```
extra-deps: [ ConfigFile-1.1.4
            , gi-harfbuzz-0.0.4
            , env-locale-1.0.0.1
            , gtk3-0.15.4
            , stm-2.5.0.0
            , hgettext-0.1.31.0
            , glib-0.13.8.1
            , pango-0.13.8.1
            , gio-0.13.8.0
            , gi-pango-1.0.24
            , haskell-gi-0.25.0
            , haskell-gi-base-0.25.0
            , gi-glib-2.0.25
            , gi-cairo-1.0.25
            , gi-atk-2.0.23
            , gi-gdk-3.0.24
            , gi-gdkpixbuf-2.0.26
            , gi-gio-2.0.28
            , gi-gobject-2.0.26
            , gi-gtk-3.0.37
            , gi-graphene-1.0.3
            , gi-gmodule-2.0.1
            , gi-gsk-4.0.3
            , ansi-terminal-0.11
            , tagsoup-0.14.7
            ]
```
I was able to compile after this.

**Comment by mitchell-gil96** [comment]
Have not had a chance of compiling this commit, but the function ‘HarfBuzz.Callbacks.C_FontGetGlyphExtentsFuncT’ does exist in gi-harfbuzz 0.0.3 documentation. Ill test a compile on the latest official commit sometime this week, but im skeptical the harfbuzz compiling error is from 0.0.3 being bugged.

gi-harfbuzz documentation for 0.0.3:
https://hackage.haskell.org/package/gi-harfbuzz-0.0.3/docs/GI-HarfBuzz-Callbacks.html#g:signal:FontGetGlyphExtentsFuncT

**Comment by phuhl** [comment]
Ah, sorry for not responding. I am burried in work, currently, so I want be able to look at it, ATM. But if you guys find a fix and create a working PR, I am more than happy to merge it

**Comment by phuhl** [comment]
Should be fixed by new release
