### ISSUE TITLE
AUR package 1.6.0-1 does not build on 5.3.7-arch1-1-ARCH

### ISSUE THREAD

**Issue by ddickstein** [phuhl/linux_notification_center#17]
`yay -S deadd-notification-center` fails for me due to a glib error in the build step.

Version: 1.6.0-1
OS: 5.3.7-arch1-1-ARCH
Hardware: MacBookPro11,4

Possibly related: https://github.com/gtk2hs/gtk2hs/issues/276

[Build Log](https://github.com/phuhl/linux_notification_center/files/3757039/deadd.log)

**Comment by rayzorben** [comment]
Also having this issue. Tried deadd-notification-center-bin but then it complains with

```
deadd-notification-center                                     
notificationDaemon started
/bin/sh: deadd-notification-center-startup: command not found
```

**Comment by rayzorben** [comment]
Looks like it is failing on this commit: https://github.com/GNOME/glib/commit/f0fb7b77a13e5fc9a5053f0b11264d1af9a853cc#diff-f09e8d680eebc6332196f01509b682e5

**Comment by phuhl** [comment]
> Also having this issue. Tried deadd-notification-center-bin but then it complains with
> 
> ```
> deadd-notification-center                                     
> notificationDaemon started
> /bin/sh: deadd-notification-center-startup: command not found
> ```

Hey, this might be due to your (the preset) configuration. You might want to create a configuration-file whith an empty ```startupCommand``` or create a file ```deadd-notification-center-startup``` somewhere where the PATH is set to.
But anyways, this should not crash the noti-center, so this should be fixed...

**Comment by phuhl** [comment]
> `yay -S deadd-notification-center` fails for me due to a glib error in the build step.
> 
> Version: 1.6.0-1
> OS: 5.3.7-arch1-1-ARCH
> Hardware: MacBookPro11,4
> 
> Possibly related: [gtk2hs/gtk2hs#276](https://github.com/gtk2hs/gtk2hs/issues/276)
> 
> [Build Log](https://github.com/phuhl/linux_notification_center/files/3757039/deadd.log)

I am quite busy currently, and I am not sure, if I can do much about this, other than to file an issue with gtk2hs or somebody, so I won't fix it soon, sorry :(

But you can try the binary version which should work. Read my comment above for that.

**Comment by ddickstein** [comment]
I've since updated my packages and am currently running `5.4.3-arch1-1`, and I still am unable to build but am failing at a different point. Since this doesn't seem to be obviously related to glibc I'm happy to close this issue and create a new one - I'm not sure how to reproduce the original issue I was having (or whether the current place where the build fails comes before or after the glibc step).

```
gi-pango                 > [83 of 93] Compiling GI.Pango.Structs.AttrShape
gi-pango                 >
gi-pango                 > /tmp/stack-b0fef13ed2fcccea/gi-pango-1.0.16/GI/Pango/Structs/AttrShape.hs:519:88: error:
gi-pango                 >     Variable not in scope:
gi-pango                 >       destroyFunc :: FunPtr GLib.Callbacks.C_DestroyNotify
gi-pango                 >     |
gi-pango                 > 519 |     result <- pango_attr_shape_new_with_data inkRect' logicalRect' data_ maybeCopyFunc destroyFunc
gi-pango                 >     |                                                                                        ^^^^^^^^^^^
gi-pango                 >

--  While building package gi-pango-1.0.16 using:
      /tmp/stack-b0fef13ed2fcccea/gi-pango-1.0.16/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1


--  While building package glib-0.13.6.0 using:
      /tmp/stack-b0fef13ed2fcccea/glib-0.13.6.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 3/9
make: *** [Makefile:12: stack] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by phuhl** [comment]
I am currently packed with work for my masters thesis so I won't be able to look into it, sorry :( There is another issue #21 related to a failing build so I will close this one for now. If you just want to install, there is a binary AUR package ( deadd-notification-center-bin ) that should install, but I currently don't have the resources to make the non-binary one work.
