### ISSUE TITLE
Notification Button Styling

### ISSUE THREAD

**Issue by balajsra** [phuhl/linux_notification_center#170]
Following up on https://github.com/phuhl/linux_notification_center/discussions/153#discussioncomment-919316.

The buttons in pop-up notifications are currently following the styling specified in `.userbutton`, `.userbutton:hover`, `.userbuttonlabel`, and `.userbuttonlabel:hover`.

![image](https://user-images.githubusercontent.com/22876640/123424828-5cdda000-d58f-11eb-967f-3d9e6e76862a.png)

It would be good to have this styling be under `.userbutton.notification`.

![image](https://user-images.githubusercontent.com/22876640/123424848-6404ae00-d58f-11eb-87fd-e45a6cd178dd.png)

**Comment by mikenrafter** [comment]
I, too, am facing this bug/issue...
![image](https://user-images.githubusercontent.com/88250914/142519276-da7a3c0b-d029-4e3d-8ec1-6de52ad35117.png)
I've tried to circumvent it using clever CSS techniques, but so far haven't been able to.
