### ISSUE TITLE
No Symbol icon appears

### ISSUE THREAD

**Issue by Gasu16** [phuhl/linux_notification_center#179]
Hello,
I installed linux notification center and I find it awesome! Unfortunately I encountered an error which I'd like to expose, currently, when I receive notifications from _Whatsapp_ or _Telegram_, it displays the following _No Symbol_ icon on a blank page:
![image](https://user-images.githubusercontent.com/28620328/146658745-ebb608eb-dc4b-419a-a983-6873853ec6cf.png)
Is not an error itself actually, but I think is quite annoying, how can I get rid of it? I'd like to simply hide it when notification appears.
Is it possible?
Thank you!

**Comment by phuhl** [comment]
Hi @Gasu16,

if you are willing to build manually, you can check out the PR https://github.com/phuhl/linux_notification_center/pull/138 which has extended scripting capabilities (but the config format is different). With the scripting from the PR you could easily change or remove the image

**Comment by phuhl** [comment]
Closing as #138 has been merged a long time ago and this can be resolved through scripting
