### ISSUE TITLE
deadd-notification-center: Prelude.head: empty list

### ISSUE THREAD

**Issue by xircon** [phuhl/linux_notification_center#184]
Getting the above error, yesterday all was good.  Have tried rebuilding the package, same issue - any ideas?

edit - it is the update 1.7.3.r101.g712b8ef-1 => 1.7.3.r108.g318d5c2-1 (am using chaotic-aur)

**Comment by phuhl** [comment]
Hi @xircon, if the error persists despite the recently merged PR, please reopen

**Comment by xircon** [comment]
Yep, fixes the problem.

**Comment by RRRRRm** [comment]
Same problem on 1.7.3.r112.g39fed9c

**Comment by phuhl** [comment]
Hi @RRRRRm, what locale are you using?

**Comment by RRRRRm** [comment]
Thank you! I set `LANG=zh_CN.UTF-8` before. When `LANG` is set to `en_US.UTF-8`, it works.

**Comment by phuhl** [comment]
Nice that it works. Should fail a bit more gracefull though...
