### ISSUE TITLE
Indicate when a notification is inactive

### ISSUE THREAD

**Issue by mikenrafter** [phuhl/linux_notification_center#191]
<del>

bug:
When clicking on an action button inside the notification center, no action happens... This' easily reproducible, and definitely should not be the way it is.

guess at fix:
My guess is that the notification object inside the notification center is treated differently than the one outside it, and therefore the hooks on the buttons disappear.

</del>

## feature request:
As a slight aside, notifications that have lost their parents do, and definitely should stay inside the notification center. However, they should have a CSS attribute/label specifying that they are no longer active, and pressing them won't do anything.

**Comment by phuhl** [comment]
Might it be, that the notification has closed already and nobody is listening to the notification anymore?

**Comment by mikenrafter** [comment]
Hm, actually, after re-testing, this issue has gone, perhaps I placebo-ed myself?  
Regardless, having a way to know if a notification has gone inactive though – that'd be useful.

**Comment by mikenrafter** [comment]
After re-visiting this, I'm unsure how feasible this would actually be. Unfortunate.
