### ISSUE TITLE
Build failing on arch linux

### ISSUE THREAD

**Issue by renanbrayner** [phuhl/linux_notification_center#194]
I downloaded the files in the AUR for the deadd-notification-center-git pkg but ghc is panicking
```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.4.4 for x86_64-unknown-linux):
        Prelude.chr: bad argument: 1526726659
```
any workarounds for this?

**Comment by renanbrayner** [comment]
I tried just now to use the 1.7.2 version, but I'm getting the same error :(

**Comment by phuhl** [comment]
Hm, "(the 'impossible' happened)" sounds like this is a ghc bug... Try opening a ticket upstream?

**Comment by phuhl** [comment]
> Thank you for this program, I love it
Thanks, my pleasure.

As it is running now, it's all good, but there is a binary package, you could install, if you prefer packages: deadd-notification-center-bin.

**Comment by renanbrayner** [comment]
> As it is running now, it's all good, but there is a binary package, you could install, if you prefer packages: deadd-notification-center-bin.

My CSS config don't work with the deadd-notification-center-bin, only with the git one, but ty for the advice

**Comment by phuhl** [comment]
Should be resolved with new version
