### ISSUE TITLE
binary releases

### ISSUE THREAD

**Issue by paperbenni** [phuhl/linux_notification_center#20]
The dependencies for compiling this are enormous. It is not something that your average ubuntu user will want to go through, even if he is smart enough to use a tiling wm. As this only really needs a single executable and from my testing, a binary compiled on arch works just fine on ubuntu. 
A buildbot or just a manually compiled binary in the github releases would be really helpful I think.

**Comment by phuhl** [comment]
Hi, thanks for the feedback. Did you checkout the AUR-package deadd-notification-center-bin? This is a binary, that I created some time ago due to reoccurring build issues, that sometimes are kindof out of my reach to resolve :/ If the binary AUR package does not install properly, feel free to reopen the issue.

**Comment by ywpkwon** [comment]
Hi @phuhl , I'd like to try the binary package on Ubuntu. Could you please tell me how to use it? I went to the "deadd-notification-center-bin" link and clicked "download snapshot". I got a .tar.gz file, unzipped it, and I got a folder "deadd-notification-center-bin" with PKGBUILD file. 

So, now how can I install this PKGBUILD file?

**Comment by phuhl** [comment]
Hi @ywpkwon,
first of all, today I released a new version with a bugfix in it, I'd recommend you use that one.

To install the binary version manually, do the following:
```
tar -xvzf linux_notification_center-1.7.2.tar.gz
cd linux_notification_center-1.7.2
wget https://github.com/phuhl/linux_notification_center/releases/download/1.7.2/deadd-notification-center
mv deadd-notification-center .out
sudo make install
```

After that, you can delete the files you downloaded and unpacked. Hope it helps.

**Comment by ywpkwon** [comment]
Thanks for your update! By the way, I got an error.
````
~/Downloads/linux_notification_center-1.7.2 
➜ sudo make install                
mkdir -p /usr/bin
install -m755 .out/deadd-notification-center /usr/bin
install: cannot stat '.out/deadd-notification-center': Not a directory
Makefile:61: recipe for target 'install-stack' failed
make: *** [install-stack] Error 1
````
I think the `deadd-notification-center` (from `wget`) seemed not a directory but a file. And you do `mv  deadd-notification-center .out`. But the error message looks like treating `.out` as a directory.

I tried 
````
mkdir .out
mv deadd-notification-center .out 
````
and the issue seemed gone.

**Comment by phuhl** [comment]
Ah, true, thanks for the info, will update the README
