### ISSUE TITLE
Config: Rename section notification.pop-up -> notification.popup and add keys to docs

### ISSUE THREAD

**Issue by fecet** [phuhl/linux_notification_center#203]
Current default config only can display 3 line content like:
```
notify-send "So many lines" "line 1\nline 2\nline 3"
```
Any more lines would be displayed as "...".

It's possible to have something like "maximum_lines" to config this? Seems relevant to #110 but not sure

**Comment by phuhl** [comment]
Hey @fecet ,

it seems this behavior is implemented, but the configuration is not documented.

```hs
  -- configPopupMaxLinesInBody
    <*> inheritingThirdLevel o "notification" "pop-up" "max-lines-in-body" 3
  -- configPopupEllipsizeBody
    <*> ((/= (0 :: Int)) <$>
          inheritingThirdLevel o "notification" "pop-up" "max-lines-in-body" 3)
```

Please try in your config:
```yaml
notification:
  pop-ups:
    max-lines-in-body: <maximum lines or 0 for ellipsation disabled>
```

If that works, we need to add it to the documentation.

**Comment by fecet** [comment]
Great, that works! But there is also a 'popup' level under notification in the documentations, which can be confusing, are them truly different?

**Comment by phuhl** [comment]
Oh boy, you are right... It appears they are distinct indeed, which is not great. We should get that fixed and change pop-up to popup

**Comment by phuhl** [comment]
@fecet Please note, that I just deployed an update that fixes the naming of pop-up to popup. You might need to update your config.
