### ISSUE TITLE
Notification counter in polybar

### ISSUE THREAD

**Issue by CZemft** [phuhl/linux_notification_center#212]
Hi is there a way to have a notification counter in polybar like this
![nwg-panel](https://user-images.githubusercontent.com/102592590/222958639-37b60d79-3c20-4e0f-861d-38f1153dd98c.png)
and how would oneself do it

**Comment by phuhl** [comment]
Hi @CZemft, this is basically a duplicate of https://github.com/phuhl/linux_notification_center/issues/34. Please take a look over there.
