### ISSUE TITLE
deadd.css in home directory appears to have no effect in 2.0.3

### ISSUE THREAD

**Issue by hwangeug** [phuhl/linux_notification_center#222]
I upgraded to 2.0.3, and now, any changes made to `$HOME/.config/deadd/deadd.css` appears to have no effect.  Downgrading back to 2.0.1 restored my settings.  Might this have something to do with #221 ?

**Comment by phuhl** [comment]
Hey, good catch. It probably is #221 as the order of import seems to be wrong. I'll see what I can do about that.

**Comment by phuhl** [comment]
Should be fixed by 2.0.4, can you confirm?

**Comment by hwangeug** [comment]
Hi, I can confirm 2.0.4 does load the `dead.css` file in my xdg config directory correctly, thanks!
