### ISSUE TITLE
Notification image interferes with left margin in popup

### ISSUE THREAD

**Issue by d3adb5** [phuhl/linux_notification_center#230]
It seems the area for the notification image in popups has a non-zero width even if the widget isn't populated with any content. I'm not too sure why that happens, as the issue doesn't seem to affect notifications in the center.

From my testing, at least 3 pixels are occupied by the image widget when there isn't an image in the notification hints.

**Comment by phuhl** [comment]
Hey, could you add a screenshot? Not sure if I understand what you mean

**Comment by d3adb5** [comment]
Sure thing! Here's what I see when I send notifications on e41e9d022802b8132ed55f8bb587359e31607e72:

![image](https://github.com/phuhl/linux_notification_center/assets/8827351/25fe7438-f949-4d69-8463-6289c3b5e006)

This is what I see after the change I made in c7b34d2, which sets the image widget visibility to `False`:

![image](https://github.com/phuhl/linux_notification_center/assets/8827351/810b79de-520f-49fd-b79e-ddcc8078f89f)

Very subtle difference, but it is there. I don't really know why it happens, but if it makes it any clearer, on the Glade editor the image widget looks like it has a default minimum width (very thin line on top left):

![image](https://github.com/phuhl/linux_notification_center/assets/8827351/6a9c0e59-4d25-45d2-94e6-df0f6ec7e8c4)

**Comment by phuhl** [comment]
Got it, yeah, makes sense to me. Thank you for the PR!
