### ISSUE TITLE
how to use app-icon as image

### ISSUE THREAD

**Issue by regern80** [phuhl/linux_notification_center#245]
how can I trade places between app-icon and image so that app-icon is displayed at the left of the pop up?
![As illustrated in this image](https://github.com/phuhl/linux_notification_center/assets/81050351/5c365d69-b4d3-4b12-8c2b-9d27b157d94e)

**Comment by regern80** [comment]
I just realised that using match and script, it can be done. Here is example of a script to use notiIcon for both the app icon and the image
`#!/bin/bash

# Read notification from STDIN
noti=""
while read line; do
    noti=${noti}${line}
done < "${1:-/dev/stdin}"

# Use jq to parse JSON and get the app icon
app_icon_raw=$(echo $noti | jq -r '.icon')

# Extract the image path using sed
app_icon=$(echo "$app_icon_raw" | sed -n 's/^.*"\(\/.*\.jpg\)".*$/\1/p')

# Modify the notification by setting the app icon and adjusting the image size
echo "{\"modify\": {\"app-icon\": \"file://$app_icon\", \"image\": \"file://$app_icon\", \"image-size\": 50}, \"match\": {}}"`

**Comment by phuhl** [comment]
That's the only mechanism right now. Glad it works for you!
