### ISSUE TITLE
Issue when trying to run 

### ISSUE THREAD

**Issue by kmafeni04** [phuhl/linux_notification_center#246]
When trying to run the binary file from the terminal, I get this message.

```
No existing translations for en_US.utf8.
Consider contributing your language.
https://github.com/phuhl/linux_notification_center/tree/master/translation
Trying English instead...

Could not find English locale.
Unable to set up localization.
```

**Comment by phuhl** [comment]
Hey, how did you install deadd?

**Comment by kmafeni04** [comment]
I downloaded the binary from the releases page

**Comment by phuhl** [comment]
You'll have to run make install to install all the asset files. Take a look here: https://github.com/phuhl/linux_notification_center#install
