### ISSUE TITLE
badHead

### ISSUE THREAD

**Issue by domenkozar** [phuhl/linux_notification_center#247]
❯ deadd-notification-center 
notificationDaemon started
deadd-notification-center: Prelude.head: empty list
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/List.hs:1646:3 in base:GHC.List
  errorEmptyList, called at libraries/base/GHC/List.hs:85:11 in base:GHC.List
  badHead, called at libraries/base/GHC/List.hs:81:28 in base:GHC.List
  head, called at src/NotificationCenter.hs:139:67 in deadd-notification-center-1.7.3-8QBdZipbFUyJbEPXN3vhFW:NotificationCenter

**Comment by avdv** [comment]
I hit the same issue. Also, I am using NixOS. :smile: 

@domenkozar see https://github.com/NixOS/nixpkgs/pull/278566

**Comment by phuhl** [comment]
Hey, thanks for reporting, should have fixed that.
