### ISSUE TITLE
Virtual size of a process is huge

### ISSUE THREAD

**Issue by georgesoteriou** [phuhl/linux_notification_center#25]
![Screenshot from 2020-02-26 18-06-24](https://user-images.githubusercontent.com/7989817/75373866-09880e80-58c3-11ea-8b33-464e7e107dfe.png)

Using default config, just installed using `make install`

System: Linux pop-os 5.3.0-7629-generic #31~1581628825~19.10~f90b7d5-Ubuntu SMP Fri Feb 14 19:56:45 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Comment by phuhl** [comment]
Hi @georgesoteriou, after quickly researching the issue, I found this in the release notes of GHC (the haskell compiler used): https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/8.0.1-notes.html#runtime-system

`Note, however, that Haskell processes will have an apparent virtual memory footprint of a terabyte or so. Don’t worry though, most of this amount is merely mapped but uncommitted address space which is not backed by physical memory.`

Do you experience any kind of issues?

**Comment by georgesoteriou** [comment]
Not really just pointing it out. Thanks

**Comment by grandchild** [comment]
Right now it also has 240MiB of reserved memory. This is on the order of a Firefox tab which is a significantly more complex beast. Maybe the virtual memory thing is just a GHC quirk, but the actual memory usage is also quite large. :/
