### ISSUE TITLE
Support for inline images

### ISSUE THREAD

**Issue by avdv** [phuhl/linux_notification_center#27]
Hi.

According to the response
```py
> import notify2
> notify2.init('py3')
> notify2.get_server_caps()
['body', 'hints', 'actions', 'persistence', 'icon-static', 'action-icons', 'body-images', 'body-markup', 'body-hyperlinks']
```
I am assuming that deadd supports inline images. Alas, embedding an image with e.g.
```
<img src='/home/claudio/x.png' alt='text'/>
```
neither shows the image nor the alt text. Actually, it seems the body is completely lost...

I am using `notify-send` if that's important..

FTR, Gtk helpfully displays a warning message to this extent:

```
Failed to set text '<markup>[view] [Folder]

<img src="/home/claudio/Screenshots/shot-2020-03-04_161607.png" alt="shot"></img>
</markup>' from markup due to error parsing markup: Unknown tag 'img' on line 3 char 77
```

**Comment by avdv** [comment]
Oh, according to https://developer.gnome.org/pango/stable/pango-Markup.html - the mini markup used by Gtk label, `img` tags are not supported...

So, the simple fix would be to not report `body-images` as a capability.

**Comment by phuhl** [comment]
Hey @avdv, 
The capability description from the [desktop notification specifications](https://developer.gnome.org/notification-spec/): 

> "body-images"	The server supports images in the notifications. 

The notification center supports images so the capability is correct, I would assume. In fact, the "body-markup" capability is the troubling one. The notification center does not support the full set of specified markup-options (with the `img` tag as the only one not working). I did not see a good description of what the server is expected to do with the img-tag, tbh. The specification does not fully elaborate on that AFAIK.

But I will leave this issue open and at some point in the future, I will implement handling of img-tags. Until then, you can fall back to the other ways of inserting images into notifications, which all are supported. Or do you have a use case where that is not possible?

**Comment by phuhl** [comment]
>>    "body-images" | The server supports images in the notifications.

> Likewise, this says if the server supports images in the body.

No, it says (quite literally) `The server supports images in the notifications.` It does.

> And, instead of not displaying the body text at all, those tags should be filtered as suggested.

Indeed, and because of that, "body-markup" is the problematic one IMHO

**Comment by avdv** [comment]
> No, it says (quite literally) `The server supports images in the notifications.` It does.

Sorry, I strongly disagree. How can you interpret "*body images*" as anything else than referring to img tags inside the **body**? (I admit the wording in the spec is not really clear...)

How about `body hyperlinks` -- that has basically the same correlation... (and the same wrong wording. It says "notification" but actually means "body", I am quite sure)

> Indeed, and because of that, "body-markup" is the problematic one IMHO

That makes no sense. The spec clearly says that you don't have to support all tags. So `body-markup` does not mean "I support *all* tags", it just means "Hey, I support markup and will render it somehow".

---

For example, dunst does not report `body-images` but does support app icons / images. Same for the mate-notification-daemon.

lxqt-notificationd supports inline images and thus reports the `body-images` capability.

**Comment by phuhl** [comment]
Ok, I see your point. One thing that is troubling me, though, is that the server supports more than just app icons. It supports app icons and additional images specified by the `image-path` and `image-data` hints. Maybe there is no possibility to report that capability within the protocol. Should the `body-image` indeed refer to inline images, than you are probably right. I will merge your PR but I don't know, when I will publish the next update to AUR (but from your other PR, I assume you are on nixOS anyways).

Concerning the markup, the specification states:

> The following tags should be supported by the notification server. Though it is optional, it is recommended. Notification servers that do not support these tags should filter them out. 

The current application appears (as you mentioned) to throw away the body with img-tags in it, instead of stripping out the img-tags. So there is an improvement to be made.

**Comment by avdv** [comment]
> Ok, I see your point. One thing that is troubling me, though, is that the server supports more than just app icons. It supports app icons and additional images specified by the `image-path` and `image-data` hints. Maybe there is no possibility to report that capability within the protocol.

I think so. Probably because they are optional anyway and a server can simply choose to ignore them. Not so for the body, because there should be some means to determine what contents a client can send in...

**Comment by MyriaCore** [comment]
wait, @phuhl  ff1c647 doesn't implement *inline* images, correct? `<img>` tags seem to be stripped even when the markup setting is true, and 8b77f79 does not appear to have been reverted.

**Comment by phuhl** [comment]
@MyriaCore It does not display the images _inline_, thats true. But it displays them. Fixing that should be a new issue, though.
