### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by YodaEmbedding** [phuhl/linux_notification_center#31]
Dunst-like [shortcuts](https://wiki.archlinux.org/index.php/Dunst#Shortcuts) would be great:

```bash
ctrl+space        close notification
ctrl+shift+space  close all notifications
ctrl+grave        pop notification from history
```

**Comment by phuhl** [comment]
Thanks for reporting. Take a look at the section [Usage](https://github.com/phuhl/linux_notification_center#usage) of the readme. I added something like that. If you need further keybindings, feel free to reopen the issue.
