### ISSUE TITLE
Reactivate notification

### ISSUE THREAD

**Issue by leoperegrino** [phuhl/linux_notification_center#38]
A fresh install of the program gave notifications with buttons for not showing the pop-up again. I clicked on it when internet connected but it was not intended. How can I start receiving the internet ones again?

**Comment by phuhl** [comment]
Hey, the buttons are shown  when the program that sends the  notification requests them. That means, if there was a button, to not show notifications, this button came from the program, that send the notification. Take a look at that program and it's settings.

Hope, it helps

**Comment by leoperegrino** [comment]
It helped. I just had to reactivate within the network manager applet. Thank you for your patience.
