### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by f3bruary** [phuhl/linux_notification_center#39]
I'm getting this when I run deadd-notification-center after following the instructions from the README:

`deadd-notification-center: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by deadd-notification-center)`

**Comment by tiega** [comment]
Ubuntu 18.04 has glibc 2.27 installed, and you don't want to mess with that or you'll risk breaking your system. You can build from source by first installing Haskell Stack (https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64-static.tar.gz), the other dependencies (cairo, pango, gobject-introspection, gtk3) then running 
```
make
sudo make install
```
source: just built this project on Ubuntu 18.04

**Comment by pascaldls** [comment]
Same problem on linux mint

**Comment by pascaldls** [comment]
Now works on mint20

**Comment by eater** [comment]
Here's a binary for Ubuntu 18.04. 
[deadd-notification-center.zip](https://github.com/phuhl/linux_notification_center/files/5287467/deadd-notification-center.zip)

**Comment by phuhl** [comment]
I will close this for now, as this appears to be resolved. If it is not, please reopen
