### ISSUE TITLE
Don't close after moving mouse away from notification center

### ISSUE THREAD

**Issue by ChristianChiarulli** [phuhl/linux_notification_center#44]
Is there a way to stop the notification center from closing even after mousing over it and then moving the mouse off the center?

I didn't see anything in the config

**Comment by MyriaCore** [comment]
There isn't anything currently, although I think this is probably a good thing to add.

Another idea could be a user-configurable 'safe zone'. Like, maybe the user specifies they want 50px past the edge of the center to still keep the center up. Or, maybe there could be a time limit. IDK, but the user should *definitely* be able to turn off if they want to.

**Comment by phuhl** [comment]
Safe zone sounds like a complicated endeavor, I would advice against it. I think, being able to turn off the current behavior is a good idea. Also, I am not sure if this is possible, easily, but clicking outside of the notification center could close it as well. I think, that was my original idea anyways but the moving mouse out was just a lot easier.

**Comment by phuhl** [comment]
There is a config option for this now
