### ISSUE TITLE
followMouse doesn't work

### ISSUE THREAD

**Issue by Baennon** [phuhl/linux_notification_center#46]
Hi,
I'm on arch lnux with i3 and installed the package bin with aur.
I created a config file in ~/.config/deadd/deadd.conf copied the conf from the git and changed followmouse to true in both sections but when a notification appears it doesn't follow the mouse to the other monitor.

**Comment by rbowden91** [comment]
I think this might be fixed by https://github.com/phuhl/linux_notification_center/pull/59/commits/9b5ef813c4ef7529a20c6bcb1b9dd6e7185821f7? But I haven't attempted it yet.

**Comment by Baennon** [comment]
Thanks, will try.

**Comment by phuhl** [comment]
@Baennon could you confirm a fix or is the error still there for your?

**Comment by Baennon** [comment]
> @Baennon could you confirm a fix or is the error still there for your?

I reinstalled the the deadd-notification-center from aur with the followMouse = True in my config but still the notification doesn't follow the mouse on the monitor it's on.
