### ISSUE TITLE
Notification popup getting stuck

### ISSUE THREAD

**Issue by Almamu** [phuhl/linux_notification_center#5]
I've installed and tried the notification center and looks awesome! I'm just having an issue with the arch package. I managed to install it based on #4 on my arch installation. Everything looks like works fine but I'm having a weird issue where opening the network settings of KDE. I have two network devices configured in my system and as soon as I open It I get two notifications about the adapter getting up, one of those notifications gets stuck and It's impossible to close.

For example: https://imgur.com/tQYKBIX

The notification is still over everything but won't close anyway. Is there any log or something I can provide to help trace the issue?
I'm using i3 as window manager with compton-tryone.

(Btw the multi-monitor support works fine)

**Comment by phuhl** [comment]
Hi @Almamu, thanks for reporting. I pushed an update (that still requires the nasty fix of #4 :( ). It was a race-condition when two notifications arrived at nearly the same time, that caused the behavior. Feel free to try out the new version in the AUR and if it works for you as well, feel free to confirm and close this.

Thanks for confirming the multi monitor setup :+1:

**Comment by phuhl** [comment]
Well, "feel free to close" haha... Feel free to reopen, if it did not work ;)

**Comment by Almamu** [comment]
Thank you, It looks like it works properly!
