### ISSUE TITLE
how to dismiss notifications?

### ISSUE THREAD

**Issue by ekaunt** [phuhl/linux_notification_center#51]
I can't figure out how to dismiss notifications without clicking on them.

Brave browser keeps sending notifications and I want to be able to dismiss each notification individually when they pop up without doing the associated action (without opening the website that clicking on it opens).

How can I do this? Is it even possible?

**Comment by MyriaCore** [comment]
Yeah, dunst allows users to customize which mouse button did which actions. That'd probably be pretty valuable to have, since it is kinda hard to figure out which buttons do what currently.

**Comment by MyriaCore** [comment]
The button handling seems to happen here:

https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter/Notifications/NotificationPopup.hs#L108-L112

The `onWidgetButtonPressEvent` function is documented [here](https://www.stackage.org/haddock/lts-16.7/gi-gtk-3.0.33/GI-Gtk-Objects-Widget.html#v:onWidgetButtonPressEvent). If I understand this code properly, it's basically **ignoring** the specific event info (like which mouse button was pressed, if it was a single click or a double click, etc), doing the default action for that notification, and then closing the popup. 

This means that, with the current functionality, there's really **no** way to clear individual popups, or distinguish between clearing individual popups and performing their default actions.
