### ISSUE TITLE
Wrong behaviour after some time of use

### ISSUE THREAD

**Issue by rauldipeas** [phuhl/linux_notification_center#52]
![84297542-118f5580-ab24-11ea-97a1-5e882b78c343](https://user-images.githubusercontent.com/12108031/84319059-ca19c100-ab45-11ea-9a63-93c495ede1c7.png)

**Comment by phuhl** [comment]
Hey there, thanks for reporting.

I think, this might be the same bug as in #40 so I will close this as a duplicate. If it appears to you, that this is not the case, feel free to reopen.
