### ISSUE TITLE
How to add imap email notification like in gnome shell notification center ?

### ISSUE THREAD

**Issue by victoracho** [phuhl/linux_notification_center#55]
I would like to know if its possible to add email notifications, I've been looking for such feature so I can use it in my awesomewm themes without adding too much effort in it.

**Comment by phuhl** [comment]
Hey there. My current version of thunderbird sends notification without any modifications. What email client do you use?

**Comment by phuhl** [comment]
Will close this for now, if the issue still exists, feel free to reopen with some extra info
