### ISSUE TITLE
Force Notifications to be kept in Notification Center

### ISSUE THREAD

**Issue by Marko1000Marko** [phuhl/linux_notification_center#6]
Feature Request:

Add a feature to force some notifications to be kept in the notification center. I see you have said "The notification (if not specified in the notification otherwise) will also be shown in the notification center", so it is controlled by some flag set by the actual program issuing the notification?

Horrible hacks or workarounds are welcome

**Comment by phuhl** [comment]
Hi @Marko1000Marko,

Currently, all notifications will be in the notification center, except it is a notification that is meant to control the buttons at the lower end of the notification center. 

The only notifications that will not appear are those that have the hint `deadd-notification-center:true` set (as specified by the [Desktop Notifications Specification](https://developer.gnome.org/notification-spec/)).

Maybe I misunderstood you? What exactly do you need?

**Comment by Marko1000Marko** [comment]
Hi, thanks for the reply @phuhl 

I'm using Arch and i3wm, notifications coming from KDE Connect will appear as popups like any other notification, but they do not remain logged in the notification center for further viewing, regardless of whether I let the notification popup disappear or click it.

Notifications from Thunderbird and test notifications sent using "notify-send" pop up normally and then remain logged in the notification center until dismissed from there, I would like this functionality for KDE Connect as well

**Comment by phuhl** [comment]
Ah, I see... I totally forgot, I implemented it to listen to the `transient`-field as also specified by the [Desktop Notifications Specification](https://developer.gnome.org/notification-spec/). 

I suppose, the KDE Connect program sets `transient` to `true`, which means, it does not want the notification persisted in a notification center. Well, and deadd listens and does not persist it.

I think, the way to solve this would be similar to the way of dunst... To make notifications skriptable, in some way, by being able to specify rules for certain notifications.

The easier (but less powerfull) way would be some kind of setting to ignore the transient field completely.

I will implement one (or both) at some point, maybe today... It would also help in context of https://github.com/phuhl/linux_notification_center/issues/2

**Comment by Marko1000Marko** [comment]
Yes, I think both of those would be acceptable solutions, the setting to ignore the transient field could be used as a temporary measure while you implement scriptable notifications

**Comment by phuhl** [comment]
Hey @Marko1000Marko, you can check out https://github.com/phuhl/linux_notification_center/commit/aa9ffa5f2bd1941c73960509fff63041ed9cbcb0 and try if it works on your system.

I will push it to the AUR soon, would be nice if you could confirm that it works for you.

**Comment by Marko1000Marko** [comment]
Hi @phuhl , unfortunately it doesn't seem to be working for me, I cloned the repo again and compiled it again and then ran sudo make install, the old version was installed, was I supposed to do something else? Even after a reboot KDE connect notifications don't seem to get logged

**Comment by phuhl** [comment]
How did you change the configuration file? 
You now have the option as described in https://github.com/phuhl/linux_notification_center#notification-based-scripting-3-6 to modify the notification or to disable transient all together as described in https://github.com/phuhl/linux_notification_center#transient-notifications-6

**Comment by Marko1000Marko** [comment]
Ah, I haven't changed the config file @phuhl 

Works great, thanks! I can help you test the AUR once you update it, it wouldn't build for me when I first tried to install it using the AUR

**Comment by phuhl** [comment]
New version (1.2.0) pushed to AUR.

**Comment by Marko1000Marko** [comment]
Compiles and installs successfully for me @phuhl
