### ISSUE TITLE
Support for Gauges / Sliders in notif action UI

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#61]
I'm not sure if there's a standard for this, but it'd be cool if users could put [guages](https://wiki.ubuntu.com/NotifyOSD#gauge), or other forms of "analog actions" onto notification UIs. Even if these UI elements aren't necessarily "actionable", it'd be good to at least have the option to display them. 

Sliders are my top pick, because they could be used in an always-present notification for scrubbing through a song, video, etc. Usually, you'd need to adopt a DE's notification daemon to accomplish this, and just deal with the lack of customization options.

Non-interactable gauges could easily be implemented with an int32 "value" hint. If we wanted to provide a bit more flexibility *over* NotifyOSD, we could allow gauge to be displayed alongside text and action buttons, as currently NotifyOSD doesn't display anything other than some icons when a gauge is displayed.

**Comment by MyriaCore** [comment]
Did a bit of digging around to figure out how other notification daemons implement this. NotifyOSD does support gauges. If the notification was issued with the `x-canonical-private-synchronous` hint, and a `value` hint was also provided, the notification will be displayed with a partially filled gauge. At least, that's what their [python test function](https://bazaar.launchpad.net/~indicator-applet-developers/notify-osd/trunk/files/510/tests/notifyosd.py#L14) seems to do to create notifications with gauges:

```python
ICON_ONLY_HINT   = "x-canonical-private-icon-only"
APPEND_HINT      = "x-canonical-append"
SYNCHRONOUS_HINT = "x-canonical-private-synchronous"
VALUE_HINT       = "value"

def create_gauge_notification(title, icon, value):
	n = pynotify.Notification(title, "", icon)
	n.set_hint_string(SYNCHRONOUS_HINT, "")
	n.set_hint_int32(VALUE_HINT, value)
	return n
```

I *think*, the `x-canonical-private-synchronous` hint does something to allow the notification to communicate synchronously with the process that invoked it, which allows NotifyOSD to inform the application of an updated gauge value. I'm not sure what, though, since I'm not familiar enough with NotifyOSD or libnotify. 

I'll look into it a bit more.

**Comment by MyriaCore** [comment]
so `x-canonical-private-synchronous` in many ways seems to almost function like NotifyOSD's version of `--replaces-process`. In [this SO post](https://askubuntu.com/a/239512), it's used to replace a potentially-existing notification. The call to `notify-send` is backgrounded, which might mean that `x-canonical-private-synchronous` is still doing some kind of synchronous communication  *on top* of being NotifyOSD's `--replaces-process`. Maybe NotifyOSD tries to keep the connection to `notify-send`, and would print out any changes the user makes to the value, which is why these guys needed to background the call (since they didn't intend to do anything with those values). I'm not sure.

**Comment by MyriaCore** [comment]
Just installed NotifyOSD to give things a whirl myself. Unfortunately, NotifyOSD doesn't actually appear to do anything special other than render the gauge as a UI element. It even greys the notification out when you hover over it, just to make things clear that interaction isn't actually supported. Even so, I think using an int32 "value" hint would be a fine method of communication.

**Comment by phuhl** [comment]
A passive element for thisplaying progress thould be fairly dooable and sounds great, I aggree. An active element, aka. a slider would be possible, but as there is no standard for handling this AFAIK, no existing applications could use it. Would be a fun exercise, though. Can't implement either right now, due to time limitations, but lets keep it in mind.

**Comment by phuhl** [comment]
This is now possible, both sliders and gauges. For more info see https://github.com/phuhl/linux_notification_center#supported-hints-and-features
