### ISSUE TITLE
No button text on telegram native notification.

### ISSUE THREAD

**Issue by ahmubashshir** [phuhl/linux_notification_center#62]
Though xfce4-notifyd is showing button labels properly, deadd-notification-center isn't showing the button labels for telegram desktop native notification...<br />
![image](https://user-images.githubusercontent.com/24864366/86530964-34244c80-bedf-11ea-9ff3-bf1f11b90608.png "xfce4-notifyd")
![image](https://user-images.githubusercontent.com/24864366/86530892-9597eb80-bede-11ea-8c89-7d2307edea8d.png "deadd-notofication-center")

**Comment by phuhl** [comment]
Hey there. Thanks for reporting.

My best guess right now is, that telegram sends icons for the buttons, when it detects this capability in the notification daemon. The icons are then not recognized by the notification center and it displays missing-image icons.

I fix could be to disable the "action-icons" capability: https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter/Notifications.hs#L86 

You could comment this out and recompile, too check, if this is the case.

Will keep this open, but I can't fix it right now...

**Comment by phuhl** [comment]
Ah, take a look at #33. Seems to be the same issue. I will close this as a dup and continue the discussion in the other one. Should the telegram-issue not resolve after fixing #33, feel free to reopen!

**Comment by MyriaCore** [comment]
this is interesting, didn't even know that action icons were a thing.

**Comment by ahmubashshir** [comment]
> Hey there. Thanks for reporting.
> 
> My best guess right now is, that telegram sends icons for the buttons, when it detects this capability in the notification daemon. The icons are then not recognized by the notification center and it displays missing-image icons.
> 
> I fix could be to disable the "action-icons" capability:
> 
> https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter/Notifications.hs#L86
> 
> You could comment this out and recompile, too check, if this is the case.
> 
> Will keep this open, but I can't fix it right now...

Doesn't work after commenting it out...
