### ISSUE TITLE
Changing icon theme?

### ISSUE THREAD

**Issue by tpurde** [phuhl/linux_notification_center#64]
I have searched through both the README.org, and the example configuration file. Failing to find anything about this issue. So, is it possible to change icon themes, so we don't face issues like this?

![image](https://user-images.githubusercontent.com/62025836/88089697-1ddfe700-cb95-11ea-9dd2-a4dd2d4961c6.png)

In this image, I don't have the icon theme that is set by default, so media playback buttons show a blank icon.

Another issue I've faced is, text cuts off too quickly, and isn't well formatted. Again, I couldn't find anything about this in the configuration file.

Here is how it looks with Dunst:
![image](https://user-images.githubusercontent.com/62025836/88090235-f5a4b800-cb95-11ea-83b8-b53935ab56f2.png)

**Comment by MyriaCore** [comment]
The icons are a part of your GTK theme. So, if your system is missing icons, you should probably find out why. 

Usually if an app needs icons, it'll install them and set them up with GTK when the app installs. Some icons are kinda understood to be common to most systems with GTK, so you'll need to figure out:
1. What icons are you missing, specifically? You can figure this out by typing the following into your terminal:
   ```sh
   dbus-monitor "interface='org.freedesktop.Notifications'
   ```
   ... and playing a song through Audacious to trigger a notification. You'll probably see these icons come through inside one of the arrays. 
2. Are these icons actually on your system? If you have nemo, or some application that lets you view the icons on your system and search through them, try to find the missing icons.
   
    If you *can* find them, the bug is likely with this software. If not, then you'll have to check with whoever packaged audacious, since it might not have properly installed the icons it needed. That, or you'll want to check with whoever provided your theme.

**Comment by MyriaCore** [comment]
Regarding the formatting, I've openned up a new issue over at #75 to track that specifically.

**Comment by tpurde** [comment]
@MyriaCore 

Audacious with xfce4-notifyd won't actually give you icons in the notification, which are non-existent. What actually is supposed to show up is 3 buttons reading "Play", "Pause" and "Show".

I did try multiple icon and GTK themes with no help from that either.

**Comment by tpurde** [comment]
> Regarding the formatting, I've openned up a new issue over at #75 to track that specifically.

Thanks for that.

**Comment by MyriaCore** [comment]
> "Play", "Pause" and "Show"

Maybe these are typos? I happen don't have these either, but I don't use audacious. It's possible that the app does package the icons, but that the notif code has a typo that requests icons with capital names. 

Regardless, you should defo submit a big report to Audacious. This is still an interesting proposal - maybe we could squeeze modification of button labels into the match / modify rules. Although, dealing with icons in the modify rules has been notoriously difficult, as you can see from #68.

**Comment by tpurde** [comment]
> Maybe these are typos? I happen don't have these either, but I don't use audacious. It's possible that the app does package the icons, but that the notif code has a typo that requests icons with capital names.

Sorry, I'm kind of having some trouble following you. Could you elaborate please?

**Comment by MyriaCore** [comment]
This is rly 100% speculation, but audacious could've easily installed these icons under the names `play`, `pause`, and `show`, which would mean that `Play`, `Pause`, and `Show` don't return anything (since icon names are case sensitive). So, maybe the programmers who wrote the notification-sending code *meant* to type `play`, `pause`, and `show`, but made a typo? 

Again, 100% speculation. I really don't know what's going on, the problem could be anywhere. You should probably just poke around and try to find out what icons specifically are missing, and where you're supposed to get them. The audacious bug tracker is [here](https://redmine.audacious-media-player.org/projects/audacious/issues), their forum is [here](https://redmine.audacious-media-player.org/projects/audacious/boards), and the code for their media player is [here](https://github.com/audacious-media-player/audacious). I'm sure they won't get mad if you ask around, and possibly link this issue.

**Comment by MyriaCore** [comment]
Just tried combing thru the audacious codebase. I couldn't find much, but I'm prob just super unfamiliar w/ the codebase.

**Comment by MyriaCore** [comment]
Oh my god I'm being so silly, I think you're experiencing #62

**Comment by tpurde** [comment]
> Oh my god I'm being so silly, I think you're experiencing #62

That sounds true.

Closing this issue because it's a duplicate of #62 which is a duplicate of #33.

I hope this gets fixed soon.
