### ISSUE TITLE
allow shell commands in modify strings

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#67]
### Use case

As it currently stands, notification-based scripting is useful for changing simple things about the notification, or for running shell commands that react to notifications coming in. However, more complex modifications of notification content aren't really possible. 

For example, discord currently doesn't render markdown properly in linux notifications. There's a [support request](https://support.discord.com/hc/en-us/community/posts/360071476232) open for this, but discord staff almost always drags their feet with things like this. So, as a workaround, it'd be cool to be able to modify the body of an incoming discord notification to convert from discord markdown to proper notification markup, complete with `<u>`, `<i>`, `<b>`, `<a>`, and `<img>` tags. 

You could imagine a feature like this being *incredibly* powerful.

### Proposal

So, it might make sense to ship a feature that allows the user to somehow call a shell script or shell command that would modify the intended elements of the notification. Maybe something like:

<table>

<tr>
<td>

```conf
[notification-center]
match = "title=Abc;body=abc":"app=notify-send"
modify = "transient=`echo 'test'`"
run = "":"killall notify-send"
```
</td>
<td>

```conf
[notification-center]
match = "title=Abc;body=abc":"app=notify-send"
modify = "transient=$(echo 'test')"
run = "":"killall notify-send"
```
</td>
</tr>

<td>

```conf
[notification-center]
match = "title=Abc;body=abc":"app=notify-send"
modify = "transient=$(./path/to/my/shell/script.sh)"
run = "":"killall notify-send"
```
</td>

<td>

```conf
[notification-center]
match = "title=Abc;body=abc":"app=notify-send"
modify = "transient=$(./path/to/my/shell/script.sh $transient)"
run = "":"killall notify-send"
```
</td>
</table>

A few ideas to unpack here:
- use 'subshell syntax' (`$( )` and `` ` ` ``) to invoke shell-based modifications (with backslash escapes to allow the user to use `$( )` and `` ` ` `` literally)
- expose the current values for modify-able parameters as environment variables, so the user can pass them to the script or command of their choice, or write a script that just inherits that environment and operates directly on it. 
- The shell script's stdout will be used as the new value

**Comment by phuhl** [comment]
Maybe, it would be easier to have the option to give the modify-param a shell command *instead* of the individual params.

You then could use
```sh
match = "title=Abc;body=abc":"app=notify-send"
modify = "body=abc;app=123"
run = "":"killall notify-send"
```

for simple static stuff and

```sh
match = "title=Abc;body=abc":"app=notify-send"
modify = "script=./path/to/my/shell/script.sh"
run = "":"killall notify-send"
```

where the script returns a string, that would then be parsed as if it was a static config string (e.g. body=abc;app=123).

That would be easiest to implement and quite powerful

**Comment by phuhl** [comment]
Added by new config format
