### ISSUE TITLE
Better Default Text Formatting in Popups

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#75]
The default formatting for text in popups is honestly kinda not great:

<table>
<tr>
<th>Linux Notif Center</th>
<th>Dunst</th>
</tr>

<tr>
<td>

![image](https://user-images.githubusercontent.com/35076430/90081726-1f0bbc00-dcdc-11ea-9d2b-3684ce9288be.png)
</td>
<td>

![image](https://user-images.githubusercontent.com/35076430/90081734-2206ac80-dcdc-11ea-9349-9b269152df88.png)
</td>
</tr>
</table>

* Screenshots courtesy of @tpurde

A few notes:
- Body text shouldn't grow the size of the notification. Instead, it should be cutoff with `(...)`. 
- The image should be centered vertically by default. The vertical alignment should also be configurable. 
- There should be configurable margins around the image.

**Comment by phuhl** [comment]
Yeah, that is actually quite a pain.

How this works is, that I use glade to create the glade files that serve as the template for the windows. I could, for the love of god, not figure out, how to get them to display properly in all the ways I wanted. If I center the image horizontally, some other issues appear (forgot, which ones).

**Comment by tpurde** [comment]
Making the notification bigger somewhat fixed this issue, but I think we should be able to set the notification size to 0 just like on Dunst, so the notification's size would depend on the text in it.

**Comment by MyriaCore** [comment]
> we should be able to set the notification size to 0 just like on Dunst, so the notification's size would depend on the text in it.

For sure, I'd just like to point out that I've had a LOT of motifs that grow way too large with the text inside. On instant messenger apps, some of my friends text in long paragraphs, and the pop-up will try to cram the whole message in there. Truncating the message solved the problem for sure. I think we could probably also implement a 'more' button to expand the whole thing.

**Comment by tpurde** [comment]
@MyriaCore 

Your "more" button proposal sounds pretty great to have!

**Comment by MyriaCore** [comment]
This is kinda the effect of just allowing text to scale the popup uninhibited

![image](https://user-images.githubusercontent.com/35076430/90262281-1d491200-de1c-11ea-8b68-374ab60b5ad6.png)

**Comment by MyriaCore** [comment]
A popup should **not** be this long lol

**Comment by MyriaCore** [comment]
I'm thinking a bit about styling here. Do you guys think I should make notification action buttons be centered relative to the whole notification window, as opposed to just centered relative to the summary & body (which is what it is now)? 

My reasoning here is that centering the action buttons relative to the summary & body only really looks nice if the summary, body, *and* buttons do not exceed the height of the image to the left. If they do, it looks kinda like the image feels kinda sectioned off, and the notification feels like it can be nicely split in half between the image, and the other stuff to the right. When the image is smaller, though, then it can't really be sectioned off, since everything else dwarfs it. The buttons add a considerable height difference, and seem to push things over the edge very often.

**Comment by MyriaCore** [comment]
The end result might look something like this:
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>

<tr>
<td>

![image](https://user-images.githubusercontent.com/35076430/91473974-a1ad8300-e867-11ea-9a8a-d18181055413.png)
</td>


<td>

![image](https://user-images.githubusercontent.com/35076430/91473900-88a4d200-e867-11ea-9452-c1e6fe079cdd.png)
</td>
</tr>
</table>

I should note that the image on the left would still be vertically centered relative to the summary & body of the notif. It'll just be like the buttons are in their own place.
