### ISSUE TITLE
How to test action icons?

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#81]
I thought it should be something like:

```sh
notify-send.py 'Action Icon Test' 'Are action icons useful?' \
  -a 'action icons' -i raindrop  \
  --hint 'bool:action-icons:true'  \
  --action '1:stock_yes' &
```

but this just displays the label text `stock_yes`.

**Comment by phuhl** [comment]
Hm, looks about right, are you sure the icon exists?

**Comment by phuhl** [comment]
This works for me:
```
 notify-send.py "And buttons" "Do you like buttons?" --hint boolean:action-icons:true --action yes:face-cool no:face-sick  
```

**Comment by MyriaCore** [comment]
Rip lol, I'll test tommorow and close this issue.

**Comment by MyriaCore** [comment]
oml it totally does. TY lol

**Comment by MyriaCore** [comment]
Reopening cause I think it might be beneficial to have a little section in the readme about this!
