### ISSUE TITLE
Create an AUR git package

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#84]
Name it something like `deadd-notification-center-git` and have it track the head of master. This way, users who want recent updates don't have to build this software outside their package manager. 

It would also mean less people complaining about bumping the version in the AUR.

**Comment by mitchell-gil96** [comment]
Yes please. The latest build in AUR is from feburary something, and contains things like glitchy disappearing notifications, spinning cursor, etc etc. I'm never bothered posting bug reports due to the sheer number of commits since that build which im assuming fixed most of those issues.

**Comment by phuhl** [comment]
I don't think, we need yet another aur package (we have two) to maintain. I will push a release to aur in the near future.

**Comment by resolritter** [comment]
Do the packages automatically get rebuilt on tagged Github releases or is it manual?

It it's the former, then I think a solution could be to simply tag more often.

**Comment by resolritter** [comment]
About `*-git` style packages, they're not as good of a fit for Haskell projects IMO because Haskell is takes so long to compile and download everything. As a user I'd much rather have the `*-bin` version be constantly updated.

I agree with @phuhl  that there isn't a _need_ for a third package currently. Maybe you could have the binary package be the "stable" one and make the current  `deadd-notification-center` into `deadd-notification-center-git`.

**Comment by phuhl** [comment]
We have a bin package, but they are all out of date. I don't think  having one stable one not is a solution I can provide.  I can't even keep them up to date equally as you can see 😂

**Comment by MyriaCore** [comment]
> I can't even keep them up to date equally as you can see 😂

This is kinda why I think a git package would work out nicely. This way you wouldn't have to worry about bumping the AUR version, since it'd just update automatically every time a  new commit hits master.

I do agree that more binary updates would be nicer, though.

**Comment by phuhl** [comment]
Ok, maybe I don't know how aur git packages work  I assumed, I had to keep the aur git up to date just as with normal aur packages... Maybe, I should research that.

**Comment by MyriaCore** [comment]
I may be uninformed too, but this is how I think they worked. If this isn't the case, I might try learning travis-ci or something so we don't have to worry about it.

**Comment by mitchell-gil96** [comment]
it in fact, is exactly how they work, the pkgbuild basically states something like "source[=$URL_to_project.git" and "sha1sums=('SKIP')"

**Comment by mitchell-gil96** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=i3-git
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=picom-git

Ive linked two -git package versions of big projects as a reference to use. If i have a chance, i'll see if i can make an AUR PKGBUILD later today and someone else test it (stack is broken in my machine and im not going through stack hell again to test this thing).

**Comment by MyriaCore** [comment]
I've never made a PKGBUILD before, but maybe this would work as a base? @mitchell-gil96 lmk if this looks good to you

```sh
# Maintainer: Philipp Uhl <philipp.uhl@rwth-aachen.de>

pkgname=deadd-notification-center-git
_gitname='linux_notification_center'
# pkgver=1.7.0 # TODO: FIX
pkgrel=1
pkgdesc="Customizable notification-daemon with notification center"
url="https://github.com/phuhl/linux_notification_center"
license=("BSD")
arch=('x86_64')
depends=('gobject-introspection-runtime' 'gtk3')
makedepends=('stack' 'cairo' 'pango' 'gobject-introspection')
provides=('deadd-notification-center')
conflicts=('deadd-notification-center-bin' 'deadd-notification-center')
source=('git://github.com/phuhl/linux_notification_center')
sha1sums=('SKIP')

# https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git
pkgver() {
  cd "$srcdir/$_gitname"
  git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
  cd "${srcdir}/${_gitname}"
  tar -zxvf "${pkgname}-${pkgver}.tar.gz"
}

build() {
  cd "${srcdir}/${_gitname}"
  make
}

package() {
  cd "${srcdir}/${_gitname}"
  make DESTDIR="$pkgdir" install
}
```

**Comment by mitchell-gil96** [comment]
ive never made a pkgbuild either and am currently working on this one.

The one you posted defeats the purpose of -git. It still calls for the tar.gz that phuhl posts on the releases folder rather than pulling what is essentially a git clone command and then running the make file in there

**Comment by MyriaCore** [comment]
Not sure how the `pkgver()` function works - I think it should just be a preprocessor thing, and maybe this is all we'd need to submit, but idk.

**Comment by mitchell-gil96** [comment]
heres what i have so far, its not yet complete.

# Maintainer: Philipp Uhl <philipp.uhl@rwth-aachen.de>

_pkgname=linux_notification_center
pkgname="${_pkgname}-git"
pkgver=1.7.2.r58.g6ff34b3
pkgrel=1
pkgdesc="Customizable notification-daemon with notification center"
url="https://github.com/phuhl/linux_notification_center"
license=("BSD")
arch=('x86_64')
depends=('gobject-introspection-runtime' 'gtk3')
makedepends=('stack' 'cairo' 'pango' 'gobject-introspection')
conflicts=('deadd-notification-center-bin' 'deadd-notification-center')
source=("git+${url}.git")
md5sums=("SKIP")

pkgver() {
  git -C "${_pkgname}" describe --long --tags | sed "s/-/.r/;s/-/./g"
}

prepare() {
  git -C "${_pkgname}" submodule update --init --recursive
  mkdir -p "${_pkgname}/build"
}

build() {
    cd "${_pkgname}/build" || exit 1
    make
}

package() {
    cd "${_pkgname}/build"
    make DESTDIR="$pkgdir" install
}

**Comment by MyriaCore** [comment]
> ive never made a pkgbuild either and am currently working on this one.
> 
> The one you posted defeats the purpose of -git. It still calls for the tar.gz that phuhl posts on the releases folder rather than pulling what is essentially a git clone command and then running the make file in there

oh yeah forgot to get rid of the prepare step, MB. 

```sh
# Maintainer: Philipp Uhl <philipp.uhl@rwth-aachen.de>

pkgname=deadd-notification-center-git
_gitname='linux_notification_center'
# pkgver=1.7.0 # TODO: FIX
pkgrel=1
pkgdesc="Customizable notification-daemon with notification center"
url="https://github.com/phuhl/linux_notification_center"
license=("BSD")
arch=('x86_64')
depends=('gobject-introspection-runtime' 'gtk3')
makedepends=('stack' 'cairo' 'pango' 'gobject-introspection')
provides=('deadd-notification-center')
conflicts=('deadd-notification-center-bin' 'deadd-notification-center')
source=('git://github.com/phuhl/linux_notification_center')
sha1sums=('SKIP')

# https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git
pkgver() {
  cd "$srcdir/$_gitname"
  git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "${srcdir}/${_gitname}"
  make
}

package() {
  cd "${srcdir}/${_gitname}"
  make DESTDIR="$pkgdir" install
}
```

The other ones you posted didn't seem to call git clone, so I assume that the system will do that automatically, since we made the source `git://...`, right?

**Comment by mitchell-gil96** [comment]
im viewing more -git pkgh builds such as lightdm, and they all basically mkdir a /build directory in the build() or prepare() step, the run git -C pkgname, cd into the build folder then run make

**Comment by MyriaCore** [comment]
aight, makes sense. I'll let you do your magic!

**Comment by mitchell-gil96** [comment]
no, dont do that. Keep investigating pkgver. One of the ones i linked runs a commit loop to determine pkgverwsion number (forgot which one) so ignore that completely. Im just viewing a bunch of -git pkgs in aur on projects i can think of like lightdm, picom, i3, etc etc

**Comment by mitchell-gil96** [comment]
ok, i think i got it. Can you try building by basically git cloning the aur package, replacing the pkgbuild with the one im about to post then build?

Mine is currently making stack which i know will fail at building gi-pango in about 10 minutes, but the important part is that it went to building stack just like a normal build would.

'''
# Maintainer: Philipp Uhl <philipp.uhl@rwth-aachen.de>

_pkgname=linux_notification_center
pkgname="${_pkgname}-git"
pkgver=1.7.2.r58.g6ff34b3
pkgrel=1
pkgdesc="Customizable notification-daemon with notification center"
url="https://github.com/phuhl/linux_notification_center"
license=("BSD")
arch=('x86_64')
depends=('gobject-introspection-runtime' 'gtk3')
makedepends=('stack' 'cairo' 'pango' 'gobject-introspection')
conflicts=('deadd-notification-center-bin' 'deadd-notification-center')
source=("git+${url}.git#branch=master")
md5sums=("SKIP")

build() {
    cd "${_pkgname}"
    make
}

package() {
    cd "${_pkgname}"
    make DESTDIR="$pkgdir" install
}

'''

**Comment by mitchell-gil96** [comment]
```
# Maintainer: Philipp Uhl <philipp.uhl@rwth-aachen.de>

_gitname=linux_notification_center
pkgname=("${_gitname}-git")
pkgver=1.7.2.r58.g6ff34b3
pkgrel=1
pkgdesc="Customizable notification-daemon with notification center"
url="https://github.com/phuhl/linux_notification_center"
license=("BSD")
arch=('x86_64')
depends=('gobject-introspection-runtime' 'gtk3')
makedepends=('stack' 'cairo' 'pango' 'gobject-introspection')
conflicts=('deadd-notification-center-bin' 'deadd-notification-center')
source=("git+${url}.git#branch=master")
md5sums=("SKIP")

build() {
  cd "${srcdir}/${_gitname}"
  make
}

package() {
  cd "${srcdir}/${_gitname}"
  make DESTDIR="$pkgdir" install
}

```

small change, I added srcdir in case aur or package manager is not cd'ed into srcdir, it wont find _gitname

Basically its identical to the latest version you posted @MyriaCore except i removed the pkgver check since it limits going with the latest commits as a whole, and will potentially almost always fail

**Comment by MyriaCore** [comment]
wait, do we not need to do something with git clone? I'll making with this.

**Comment by MyriaCore** [comment]
BTW, is there a reason we're changing the name to `linux_notification_center`? I get that the name change did kinda already happen, but I worry that we'll lose parity between `deadd-notification-center` and `deadd-notification-center-bin`. Plus, the configs are read from `$XDG_CONFIG/deadd/deadd.conf` still.

**Comment by MyriaCore** [comment]
Just tested it, `makepkg` seems to work perfectly.

**Comment by mitchell-gil96** [comment]
One does not need to specifically call git clone, apparently just pointing source to the git file seems suffient.
Pkgversion function servers to auto update the aur version to the latest commit.

I changed the name because ultimately its pulling from a repo titled "linux_notification_center".
If it creates a conflict, merely renaming pkgname to deadd-notification-center should be sufficient for the conf files to still call for deadd.

The rest of the pkgbuild needs to reference linux instead of deadd because when it git clones, it will create a directory named after the master repo name, and needs to cd into that folder named after the repo.

**Comment by MyriaCore** [comment]
I mean I'm all for a rename, but I think we gotta rename everything at once. Maybe we'll open a new issue for that.

**Comment by mitchell-gil96** [comment]
For now, to maintain parity, renaming the second line "pkgname" to deadd might be necessary due to the refences anything might contain to "deadd"

_gitname must stay linux however to reference the name of the repo when building.

**Comment by MyriaCore** [comment]
Yeah, makes sense. This is the version I've gotten to work:

```sh
# Maintainer: Philipp Uhl <philipp.uhl@rwth-aachen.de>

_gitname="linux_notification_center"
pkgname=deadd-notification-center-git
pkgver=1.7.2.r58.g6ff34b3
pkgrel=1
pkgdesc="Customizable notification-daemon with notification center"
url="https://github.com/phuhl/linux_notification_center"
license=("BSD")
arch=('x86_64')
depends=('gobject-introspection-runtime' 'gtk3')
makedepends=('stack' 'cairo' 'pango' 'gobject-introspection')
provides=('deadd-notification-center')
conflicts=('deadd-notification-center-bin' 'deadd-notification-center')
source=("git+${url}.git#branch=master")
md5sums=("SKIP")

pkgver() {
  cd "${srcdir}/${_gitname}"
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "${srcdir}/${_gitname}"
  make
}

package() {
  cd "${srcdir}/${_gitname}"
  make DESTDIR="$pkgdir" install
}
```

**Comment by mitchell-gil96** [comment]
Seems ready to go.
On a related note, me and several other people in the non-binary version of the package in AUR had trouble building due to gi-pango issues i mentioned in #85 so when it goes live, some people might not be able to build. But for now this specific issue can be closed.

**Comment by MyriaCore** [comment]
> Do the packages automatically get rebuilt on tagged Github releases or is it manual?
> 
> It it's the former, then I think a solution could be to simply tag more often.

IDK, actually. I think it's prob manual, since doing it automatically sounds like it'd be a CI/CD thing. Maybe the repo is zipped up automatically? 

If this is the functionality we want, and I'm right about the non-manual thing, then we could probably just try to add a travis-ci setup to autobuild for us. I still do think that having a git package might be useful though.

**Comment by mitchell-gil96** [comment]
I might be misreading this but i think ts automatic and is achieved using the pkgver() function in PKGBUILD

More info here https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function

I forgot what -git package i installed recently but it hadn't been updated since 2015 and still gave me the latest commits.

**Comment by MyriaCore** [comment]
Yeah, but they're talking about normal packages, without -git.

**Comment by MyriaCore** [comment]
hey, while I'm at it, I'm thinking of adding makedepends and provides to the other PKGBUILD's, just so there's a bit more metadata. @mitchell-gil96 do you remember if the normal `deadd-notification-center` package builds with stack, and requires the same depends as the other one? I think it does, right?

**Comment by mitchell-gil96** [comment]
I actually do not know. You're more familiar with the dependencies than I am in this regard. All i remember is that the not bin version of AUR installs stack on my behalf if i do not have it.

**Comment by MyriaCore** [comment]
Hummm, alright. I might just get rid of that bit then.

**Comment by mitchell-gil96** [comment]
I can't unfortunately. I resorted to just running the bin version of this thing in my local machine since building will always fail for me at the gi-pango step.
Non-bin in aur calls for the stack makedepend and is what installs stack in my machine when i do not have it. And that stack build installs alot of haskell package dependencies.

**Comment by MyriaCore** [comment]
stack build rly shouldn't be installing dependencies, especially not for the bin version. It should just grab deps needed to build the binary, throw them somewhere locally, build the binary, then nuke the folder the deps were stored in.

I think we're technically using stack setup, as per the makefile, so the mechanics of that could be different. IDK.

**Comment by phuhl** [comment]
> stack build rly shouldn't be installing dependencies, especially not for the bin version. 

For the bin version. it doesnt, I think

**Comment by phuhl** [comment]
> I'll prob just get rid of the lines with the makedepends. It sounds like it already works somehow anyways.

Yeah, because they are already installed. Try on a blank machine. That's when you need them!

**Comment by mitchell-gil96** [comment]
Since were talking AUR and thus specifically arch linux here, the default version of stack on their official repos is built using the multiple haskell dependencies. The bin version is relegated to an aur package. Granted, it builds and works fine for me at least. Also the build non bin version is regularly kept up to date with the latest update launched yesterday. The binary version in aur at least hasn't been updated since July.

So when editing makedepends, one must assume that the dependency is the non-bin version of stack.

**Comment by MyriaCore** [comment]
I thought makedepends and depends track other packages' provides, rather than the package name itself?

**Comment by phuhl** [comment]
> I thought makedepends and depends track other packages' provides, rather than the package name itself?

I don't know, what do you mean by that? My understanding is, that the depends field states the runtime dependencies of the package, specified by in the file (in this case the DNC) while the make dependencies are only required for the build process and can be removed after building as they are not required at runtime.

**Comment by MyriaCore** [comment]
@phuhl dw, I was talking to @mitchell-gil96. I was confused about if the depends sections specifies *packages*, or *package provides*. The `provides=packagename` is general, since the git, bin, or normal release of a package can still "provide" the same software. This is basically what allows people to feel comfortable having multiple different kinds of packages for the same software.

I thought when you depend on something, you depended on that package provide, meaning that requirement could be satisfied by a git version *or* a bin version of that package. I guess I was mistaken.

**Comment by MyriaCore** [comment]
Wait, no, [this article](https://wiki.archlinux.org/index.php/PKGBUILD#provides) makes it sound like I was right: 
> An array of additional packages that the software provides the features of

Wouldn't this mean that if you were installing stack-bin alongside deadd-notification-center or deadd-notification-center-git, the stack dependency would still be satisfied (since stack-bin provides stack)?

**Comment by phuhl** [comment]
ah, I see now, what you mean.

> Wouldn't this mean that if you were installing stack-bin alongside deadd-notification-center or deadd-notification-center-git, the stack dependency would still be satisfied (since stack-bin provides stack)?

yes, i think, that would be the case
