### ISSUE TITLE
How to translate 'button_deleteAll'  label

### ISSUE THREAD

**Issue by sjugge** [phuhl/linux_notification_center#9]
### Observed behavior

[The label Alle Löschen](https://github.com/phuhl/linux_notification_center/search?q=%22Alle+L%C3%B6schen%22&unscoped_q=%22Alle+L%C3%B6schen%22) is shown as-is on a system in `en_US.UTF-8`. However, [the date string](https://github.com/phuhl/linux_notification_center/blob/037c7e4618ca1f159f2835a5e1b34fa71f979859/notification_center.glade#L66) is translated to English.

Screenshot:

![2019-05-05--16-51-08](https://user-images.githubusercontent.com/784224/57195787-d6047e00-6f56-11e9-902f-76beb14671c1.png)

### Version and system info

* package installed: [`deadd-notification-center-bin` from AUR](https://aur.archlinux.org/packages/deadd-notification-center-bin/) 
  * version: 1.6.1-1
  * branch: `master`
  * commit: `6ca6536e4ede04de7c3b22c5fc82d9613b762b28`
  * [config](https://gitlab.com/sjugge/dotfiles/blob/master/.config/deadd/deadd.conf) (same behavior with [default config](https://github.com/phuhl/linux_notification_center/tree/037c7e4618ca1f159f2835a5e1b34fa71f979859#configuration))
* OS: Arch Linux
* Kernel: x86_64 Linux 5.0.11-arch1-1-ARCH
* WM: i3 (i3-gaps)
* GTK Theme: [oomox-Materiarch-dark [GTK2/3]](https://gitlab.com/sjugge/dotfiles/tree/master/.themes/oomox-Materiarch-dark)

### Expected behavior

Translated or translatable string for the `button_deleteAll` label. I have no clue how translations in Haskell / GTK work under the hood so tried some config options but none altered the behavior. So I assume either I'm missing something to correctly translate the label, or this is a bug.

Thanks in advance for your insights into this.

###

**Comment by phuhl** [comment]
Uhhm, as you mention it, I am surprised noone opend this issue earlier. The date is correctly translated because it uses your locale to show it nicely but the delete-all-button is hardcoded in [this](https://github.com/phuhl/linux_notification_center/blob/master/notification_center.glade) file. In order to translate it... I don't know how this is done usually. I will think about it and push a fix soon. 

Until then you could just edit the file I mentioned to your likings and recompile by hand as described in the README.

**Comment by phuhl** [comment]
In the next update, a change will be included, that fixes this issue. 
If you are interested in the details: Now there is a translation-file in the folder translation. Currently only one label seems to exist, where a translation makes sense. I only translated to German and English for now.
Thank you for reporting :)
